name: Continuous Integration

on:
  pull_request:
  push:
    branches: [ main, dev ]

jobs:
  ci:
    name: Test and Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      DB_NAME: ./.tmp/ci-test.db
      ASTRO_TELEMETRY_DISABLED: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm run test:ci

      - name: Run Production Build
        run: npm run build
